---
sidebar: sidebar 
permalink: use/capacity-add.html 
keywords: economic efficiency remediate, lifecycle planning, capacity planning, add capacity 
summary: ライフサイクル プランニングでは、予測されるデータの増加に基づいてAFFシステムの推奨事項が提供されます。予測を受け入れるか、独自の予測を入力することができます。これに基づいて、ライフサイクル プランニングでは、容量増加予測を満たし、資産構成に最適な推奨事項が提示されます。 
---
= 容量を追加
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
ライフサイクル プランニングでは、予測されるデータの増加に基づいてAFFシステムの推奨事項が提供されます。予測を受け入れるか、独自の予測を入力することができます。これに基づいて、ライフサイクル計画では、容量増加予測を満たし、資産構成に最適な推奨事項を提示します。

推奨事項の 1 つは、既存のシリアル番号に棚を追加して容量を追加することです。

見積依頼または代替オプションのリクエストとして、推奨事項をNetAppセールス チームに簡単に送信できます。

.手順
. link:../get-started/capacity-login.html["NetAppコンソールにログインする"] 。
. *キャパシティプランニング*を選択します。
. アセットの*ストレージ オプションの評価*を選択します。
. *容量の追加*を選択します。
+
資産のデータが表示されます。

+
** 予測、使用率、レイテンシの傾向、IOPS の傾向を確認します。
** 推奨事項を取得するには、[*ストレージ オプションの評価*] を選択します。
+
「容量要件の定義」ページには、現在の容量予測と予測される容量増加に基づいて推奨されるアドオン ストレージが表示されます。



. 右側のオプションのいずれかを選択します。
+
** *予測される増加に基づいてアドオンストレージを推奨*し、オプションでバッファパーセンテージを追加します。
** *カスタム データの増加に基づいてアドオン ストレージを推奨*し、推奨値ではなく必要なアドオン容量の合計を入力します。


. *続行*を選択します。
+
一連の推奨事項が表示されます。

. 選択した資産シリアル番号の推奨事項を確認します。
. 次のいずれかを実行します。
+
** 推奨事項を承認するには、[次へ] を選択します。リクエストはNetApp のセールス エキスパートに送信され、エキスパートがお客様と協力して必要な追加容量を取得します。
** 別のオプションをリクエストするには、「*代替オプションのリクエスト*」を選択し、リクエストを入力して、「*電子メールの送信*」を選択します。電子メールがNetApp のセールス エキスパートに転送され、そのエキスパートから容量要件に対応するために連絡が届きます。


. 追加容量のリクエストを確認し、[確認して送信] を選択します。
+
容量計画ステータス ページが表示されます。

. キャパシティ プランニング ステータス ページでステータスを確認します。

