---
sidebar: sidebar 
permalink: get-started/intro.html 
keywords: how NetApp lifecycle planning works, what is lifecycle planning, bluexp, hardware refresh, technology refresh, capacity, forecasted capacity, storage, forecast, economic efficiency 
summary: NetAppライフサイクル プランニングは、現在または将来的に容量が低いと予測されるクラスターを識別し、データ階層化に関する推奨事項を提供します。 
---
= ライフサイクルプランニングについて学ぶ
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
ライフサイクル プランニングでは、現在または予測される低容量のストレージ資産を評価し、ビジネス ニーズを満たすデータ階層化オプションに関する推奨事項を提供します。



== NetApp Console

ライフサイクル プランニングには、 NetApp Consoleからアクセスできます。

NetApp Consoleは、オンプレミスとクラウド環境全体にわたるエンタープライズ グレードのNetAppストレージとデータ サービスの集中管理を提供します。NetAppデータ サービスにアクセスして使用するには、コンソールが必要です。管理インターフェースとして、1 つのインターフェースから多数のストレージ リソースを管理できます。コンソール管理者は、企業内のすべてのシステムのストレージとサービスへのアクセスを制御できます。

NetApp Consoleの使用を開始するためにライセンスやサブスクリプションは必要ありません。ストレージ システムまたはNetAppデータ サービスへの接続を確保するためにクラウドにコンソール エージェントを展開する必要がある場合にのみ料金が発生します。ただし、コンソールからアクセスできる一部のNetAppデータ サービスは、ライセンスまたはサブスクリプションベースです。

詳細はこちら https://docs.netapp.com/us-en/bluexp-setup-admin/concept-overview.html["NetApp Console"]。



== ライフサイクル計画で何ができるでしょうか?

ライフサイクル計画は、次の目標を達成するのに役立ちます。

*容量情報*

* 環境内で容量が低下しているストレージ資産を特定します。
* 資産の現在の容量と予測容量を確認します。




== ライフサイクルプランニングのメリット

ライフサイクル プランニングには次のような利点があります。

* ライフサイクル イベントに近づいているシステムを特定し、テクノロジーの更新を計画するのに役立ちます
* 環境内の容量の問題に対処するための信頼できるアドバイザーの推奨事項を提供します
* 追加ストレージの計画にかかる時間を短縮




== 料金

NetApp、ライフサイクル プランニングの使用に対して料金を請求しません。

コールド データをクラウド ストレージに階層化する場合は、適用される料金についてクラウド プロバイダーに確認する必要があります。



== アクセス

この機能には、 NetApp Console(* ストレージ * > *ライフサイクル プランニング *) またはActive IQ Digital Advisor ( Digital Advisorとも呼ばれます) (* ダッシュボード * > *計画ウィジェット * > *技術更新 *) からアクセスできます。
